/**
 * Seed built-in tools to Cloudflare D1.
 *
 * Usage:
 *   pnpm run seed:builtin            # local D1
 *   pnpm run seed:builtin -- --remote # remote D1
 *
 * This script reads toolMeta from each built-in route and inserts them
 * into the database with is_builtin = 1. Safe to run multiple times (idempotent).
 */

import { execSync } from "node:child_process";
import { unlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import type { BuiltinToolMeta } from "../lib/types/tool";

// ─── Canonical list of built-in tools ────────────────────────────────────────
// Keep in sync with the toolMeta exports in app/routes/tools.*.tsx
const builtinTools: BuiltinToolMeta[] = [
	{
		id: "base64-converter",
		name: "Base64 编解码",
		description: "Encode and decode Base64 data with customizable options",
		icon: "Binary",
		category: "builtin",
		tags: ["base64", "encode", "decode"],
	},
	{
		id: "file-uploader",
		name: "文件上传",
		description: "Upload and manage files with preview and URL generation",
		icon: "Upload",
		category: "builtin",
		tags: ["file", "upload", "storage"],
	},
	{
		id: "json-diff",
		name: "JSON Diff",
		description: "比较两个 JSON 对象并可视化差异",
		icon: "GitCompare",
		category: "builtin",
		tags: ["json", "diff", "compare"],
	},
	{
		id: "json-formatter",
		name: "JSON 工具箱",
		description: "格式化、查询、对比和可视化 JSON 数据",
		icon: "Braces",
		category: "builtin",
		tags: ["json", "format", "validate", "query"],
	},
	{
		id: "jwt-decoder",
		name: "JWT 解析器",
		description: "解析 JSON Web Token，展示 Header、Payload 和签名",
		icon: "KeyRound",
		category: "builtin",
		tags: ["jwt", "token", "decode", "auth"],
	},
	{
		id: "qr-generator",
		name: "二维码生成器",
		description: "生成可自定义样式的二维码，支持多种形状、渐变色和下载格式",
		icon: "QrCode",
		category: "builtin",
		tags: ["qr", "qrcode", "generate"],
	},
	{
		id: "time-formatter",
		name: "日期时间转换器",
		description: "将日期和时间在多种不同格式之间转换",
		icon: "Clock",
		category: "builtin",
		tags: ["time", "date", "format", "convert"],
	},
	{
		id: "ua-parser",
		name: "User-Agent 解析器",
		description: "解析 User-Agent 字符串，获取浏览器、引擎、操作系统、CPU 和设备信息",
		icon: "Fingerprint",
		category: "builtin",
		tags: ["ua", "user-agent", "browser", "parse"],
	},
	{
		id: "url-encoder",
		name: "URL 编解码",
		description: "Encode and decode URLs with encodeURIComponent and decodeURIComponent",
		icon: "Link",
		category: "builtin",
		tags: ["url", "encode", "decode"],
	},
	{
		id: "url-parser",
		name: "URL 分析器",
		description: "可视化、编辑、分析和比较 URL，支持编辑参数值并生成新URL",
		icon: "Globe",
		category: "builtin",
		tags: ["url", "parse", "analyze", "query"],
	},
];

// ─── SQL generation ───────────────────────────────────────────────────────────
function escape(s: string): string {
	return s.replace(/'/g, "''");
}

function buildSql(tools: BuiltinToolMeta[]): string {
	const lines: string[] = [
		"-- Auto-generated by scripts/seed-builtin-tools.ts",
		"PRAGMA defer_foreign_keys=TRUE;",
		"",
		"-- Ensure builtin category exists",
		"INSERT OR IGNORE INTO tool_categories (id, name, description, icon, color) VALUES",
		"  ('builtin', '内置工具', 'DevShelf 内置的开发者工具', 'Puzzle', '#6366f1');",
		"",
	];

	for (const tool of tools) {
		lines.push(`-- ${tool.name} (${tool.id})`);
		lines.push(
			`INSERT OR REPLACE INTO tools (id, name, description, category, icon, is_internal, is_builtin, status, last_updated) VALUES`,
		);
		lines.push(
			`  ('${escape(tool.id)}', '${escape(tool.name)}', '${escape(tool.description)}', '${escape(tool.category)}', '${escape(tool.icon)}', 1, 1, 'active', datetime('now'));`,
		);

		// Ensure a production environment entry exists (internal route)
		lines.push(
			`DELETE FROM tool_environments WHERE tool_id = '${escape(tool.id)}';`,
		);
		lines.push(
			`INSERT INTO tool_environments (tool_id, name, label, url, is_external) VALUES`,
		);
		lines.push(
			`  ('${escape(tool.id)}', 'production', '打开', '/tools/${escape(tool.id)}', 0);`,
		);

		// Remove existing tags then re-insert (handles tag changes on re-seed)
		lines.push(`DELETE FROM tool_tags WHERE tool_id = '${escape(tool.id)}';`);
		for (const tag of tool.tags) {
			lines.push(
				`INSERT OR IGNORE INTO tool_tags (tool_id, tag) VALUES ('${escape(tool.id)}', '${escape(tag)}');`,
			);
		}
		lines.push("");
	}

	return lines.join("\n");
}

// ─── Main ─────────────────────────────────────────────────────────────────────
const isRemote = process.argv.includes("--remote");
const target = isRemote ? "--remote" : "--local";
const scriptDir = fileURLToPath(new URL(".", import.meta.url));
const sqlFile = join(scriptDir, "_builtin-tools-seed.sql");

console.log(`\nSeeding ${builtinTools.length} built-in tools to D1 (${isRemote ? "remote" : "local"})...\n`);

const sql = buildSql(builtinTools);
writeFileSync(sqlFile, sql, "utf-8");

try {
	execSync(`wrangler d1 execute DB ${target} --file="${sqlFile}"`, {
		stdio: "inherit",
	});

	// Invalidate KV cache so the new tools are visible immediately
	const newVersion = Date.now().toString();
	const kvKeys = ["tools:cache:version", "categories:cache:version"];
	for (const key of kvKeys) {
		try {
			execSync(
				`wrangler kv key put "${key}" "${newVersion}" --namespace-id=43902c8bb47b4c3a85e07eeb57eb1168 ${isRemote ? "--remote" : "--local"}`,
				{ stdio: "inherit" },
			);
		} catch {
			console.warn(`⚠ Failed to update KV key "${key}" — cache may be stale`);
		}
	}

	console.log(`\n✓ Done! ${builtinTools.length} built-in tools seeded.\n`);
	if (!isRemote) {
		console.log("  Tip: run with --remote to seed production D1.\n");
	}
} finally {
	unlinkSync(sqlFile);
}
