/**
 * Extend Cloudflare.Env with secrets that are not generated by `wrangler types`.
 * Secrets are set via `wrangler secret put <NAME>` and are not in wrangler.jsonc.
 */
declare namespace Cloudflare {
	interface Env {
		JWT_SECRET: string;
	}
}
